language: android

jdk:
 - openjdk8

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28

  licenses:
    - '.+'

script:
    - ./gradlew clean assemble check

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $ANDROID_HOME
