language: android

jdk:
 - openjdk7

android:
  components:
    - tools
    - build-tools-24.0.0
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - '.+'

script:
    - ./gradlew clean assemble --stacktrace

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
